package es.sfernandez.sqg.model.validators

/**
 * ValidationResults are generated by [Validator] as result of validate a given value.
 *
 * @param T type of value validated
 * @property type Result's type: [ValidationResultType.OK], [ValidationResultType.WARNING] y [ValidationResultType.ERROR]
 * @property msg Result's message
 * @property context The value that was validated
 */
class ValidationResult<T>
private constructor(
    val type: ValidationResultType,
    val msg: String = "",
    val context: T? = null,
){

    enum class ValidationResultType {
        /** Everything is perfect */
        OK,
        /** Something isn't right, but is not critical */
        WARNING,
        /** Something isn't right */
        ERROR,
    }

    /**
     * @return true iff type is equal to [ValidationResultType.OK]
     */
    fun isOk() : Boolean {
        return type == ValidationResultType.OK
    }

    companion object {

        /**
         * Creates a new [ValidationResultType.OK] ValidationResult
         *
         * ValidationResult of type OK have empty message and no need context
         *
         * @return a new [ValidationResultType.OK] ValidationResult with empty message and no context
         */
        fun <T> ok() : ValidationResult<T> {
            return ValidationResult(ValidationResultType.OK)
        }

        /**
         * Creates a new [ValidationResultType.WARNING] ValidationResult
         *
         * ValidationResult of type WARNING needs a message. It's possible to aggregate a context
         *
         * @param msg help message of the result
         * @param context value that has been validated. null by default
         * @return a new [ValidationResultType.WARNING] ValidationResult with the given message and context
         */
        fun <T> warning(msg: String, context: T? = null) : ValidationResult<T> {
            return ValidationResult(ValidationResultType.WARNING, msg, context)
        }

        /**
         * Creates a new [ValidationResultType.ERROR] ValidationResult
         *
         * ValidationResult of type ERROR needs a message. It's possible to aggregate a context
         *
         * @param msg help message of the result
         * @param context value that has been validated. null by default
         * @return a new [ValidationResultType.ERROR] ValidationResult with the given message and context
         */
        fun <T> error(msg: String, context: T? = null) : ValidationResult<T> {
            return ValidationResult(ValidationResultType.ERROR, msg, context)
        }

    }

}
